[dev]
  secret_key = "dev"

  [dev.server]
    scheme = "https"
    host = "localhost"
    port = 9292

    count = 1
    hot_swap = true

    event_source_retry_ms = 1000
    render_exceptions = true
    self_signed_cert = true

  [dev.metrics]
    enabled = true

[prod]
  use_bundle = true

  [prod.server]
    scheme = "http"
    host = "0.0.0.0"
    port = 3000

    event_source_retry_ms = 1000
    hot_swap = false

    count = 1
    forks = 1
    threads = 2

  [prod.metrics]
    enabled = true
    port = 9091
    host = "0.0.0.0"
