# fly.toml file generated for mayu on 2022-07-14T10:48:22-05:00

app = "mayu"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ENABLE_YJIT=false

[metrics]
  port = 9092
  path = "/metrics"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  tcp_checks = []
  http_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443
    tls_options = { alpn = ["h2"] }

  [[services.script_checks]]
    interval = 10000
    timeout = 1000
    command = "/fly/healthcheck.sh"
    restart_limit = 3
