what_needs_to_be_done = "Vad behöver göras?"
clear_completed = "Rensa färdiga"

[item]
  one = "%<count>d sak"
  many = "%<count>d saker"

[filter]
  all = "Alla"
  active = "Aktiva"
  completed = "Färdiga"
